import type { Incoming, Speaker } from "./types";

const T0 = Date.UTC(2026, 8, 26, 1, 12, 0);

let stepNo = 0;

function step(
  partial: Omit<Incoming, "messageId" | "occurredAt" | "origin" | "senderId" | "senderName" | "senderUsername" | "reveal"> &
    Partial<Incoming>,
): Incoming {
  stepNo += 1;
  return {
    senderId: partial.chatId,
    senderName: partial.chatTitle,
    senderUsername: partial.chatUsername,
    reveal: "open",
    messageId: stepNo,
    occurredAt: T0 + stepNo * 11 * 60 * 1000,
    origin: "drill",
    ...partial,
  };
}

export const DRILL_TALKS: Speaker[] = [
  {
    hiddenId: "9001",
    displayName: "林晚",
    username: "lin_edits",
    at: T0 + 3 * 11 * 60 * 1000 + 5 * 60 * 1000,
  },
];

/** Chronological drill. Same pipeline as live Telegram updates. */
export const DRILL: Incoming[] = [
  step({
    fileUniqueId: "uq-cup",
    fileId: "file-cup",
    kind: "photo",
    chatId: "-100300",
    chatTitle: "器物手记",
    chatUsername: "qiqi_weekly",
    chatType: "channel",
    caption: "晨光里的杯子",
    width: 1600,
    height: 1200,
    duration: null,
    bytes: 549_000,
    preview: "/media/cup.jpg",
    mediaUrl: null,
    visualHash: "0011223344556677",
  }),
  step({
    fileUniqueId: "uq-city",
    fileId: "file-city",
    kind: "photo",
    chatId: "-100100",
    chatTitle: "河灯日报",
    chatUsername: "hedeng_daily",
    chatType: "channel",
    caption: "雨后的桥",
    width: 1600,
    height: 1200,
    duration: null,
    bytes: 696_000,
    preview: "/media/city.jpg",
    mediaUrl: null,
    visualHash: "0123456789abcdef",
  }),
  step({
    fileUniqueId: "uq-city",
    fileId: "file-city",
    kind: "photo",
    chatId: "9003",
    chatTitle: "周助",
    chatUsername: "zhouzhu",
    chatType: "private",
    caption: "转给你：雨后的桥",
    width: 1600,
    height: 1200,
    duration: null,
    bytes: 696_000,
    preview: "/media/city.jpg",
    mediaUrl: null,
    visualHash: "0123456789abcdef",
  }),
  step({
    fileUniqueId: "uq-desk",
    fileId: "file-desk",
    kind: "photo",
    chatId: "9001",
    chatTitle: "林编辑",
    chatUsername: "lin_edits",
    chatType: "private",
    caption: "校样和印泥",
    senderId: "9001",
    senderName: "林晚",
    senderUsername: "lin_edits",
    width: 1600,
    height: 1200,
    duration: null,
    bytes: 725_000,
    preview: "/media/desk.jpg",
    mediaUrl: null,
    visualHash: "fedcba9876543210",
  }),
  step({
    fileUniqueId: "uq-desk-re",
    fileId: "file-desk-re",
    kind: "photo",
    chatId: "9001",
    chatTitle: "林编辑",
    chatUsername: "lin_edits",
    chatType: "private",
    caption: "校样再压了一版",
    senderId: "9001",
    senderName: "林编辑",
    senderUsername: "lin_edits",
    width: 1280,
    height: 960,
    duration: null,
    bytes: 210_000,
    preview: "/media/desk.jpg",
    mediaUrl: null,
    visualHash: "fedcba9876543210",
  }),
  step({
    fileUniqueId: "uq-meme",
    fileId: "file-meme",
    kind: "photo",
    chatId: "-100999",
    chatTitle: "闲聊转贴",
    chatUsername: "rumor_bin",
    chatType: "channel",
    caption: "无关的转贴",
    width: 800,
    height: 800,
    duration: null,
    bytes: 80_000,
    preview: "/media/wool.jpg",
    mediaUrl: null,
    visualHash: "2222333344445555",
  }),
  step({
    fileUniqueId: "uq-stall",
    fileId: "file-stall",
    kind: "video",
    chatId: "-100200",
    chatTitle: "夜摊影像",
    chatUsername: "yetan_studio",
    chatType: "channel",
    caption: "夜摊",
    width: 1280,
    height: 720,
    duration: 6,
    bytes: 5_900_000,
    preview: "/media/stall.jpg",
    mediaUrl: "/media/stall.mp4",
    visualHash: "abcdef0123456789",
  }),
  step({
    fileUniqueId: "uq-anim",
    fileId: "file-anim",
    kind: "animation",
    chatId: "-100100",
    chatTitle: "河灯日报",
    chatUsername: "hedeng_daily",
    chatType: "channel",
    caption: "灯火循环",
    width: 480,
    height: 360,
    duration: 2,
    bytes: 140_000,
    preview: "/media/city.jpg",
    mediaUrl: null,
    visualHash: "1111222233334444",
  }),
  step({
    fileUniqueId: "uq-wool",
    fileId: "file-wool",
    kind: "photo",
    chatId: "9002",
    chatTitle: "陈裁缝",
    chatUsername: "chen_tailor",
    chatType: "private",
    caption: "炭灰色呢料",
    width: 1728,
    height: 1152,
    duration: null,
    bytes: 794_000,
    preview: "/media/wool.jpg",
    mediaUrl: null,
    visualHash: "8899aabbccddeeff",
  }),
  step({
    fileUniqueId: "uq-room",
    fileId: "file-room",
    kind: "photo",
    chatId: "-100880",
    chatTitle: "裁缝工作室",
    chatUsername: "tailor_room",
    chatType: "supergroup",
    caption: "工作台一角",
    width: 1200,
    height: 900,
    duration: null,
    bytes: 300_000,
    preview: "/media/desk.jpg",
    mediaUrl: null,
    visualHash: "3333444455556666",
  }),
  step({
    fileUniqueId: "uq-flash",
    fileId: "file-flash",
    kind: "photo",
    chatId: "9001",
    chatTitle: "林编辑",
    chatUsername: "lin_night",
    chatType: "private",
    caption: "看完就没的一张",
    senderId: "9001",
    senderName: "林编辑",
    senderUsername: "lin_night",
    reveal: "flash",
    width: 1600,
    height: 1200,
    duration: null,
    bytes: 180_000,
    preview: "/media/city.jpg",
    mediaUrl: null,
    visualHash: "aaaa1111bbbb2222",
  }),
];
